services:
  wespeek:
    image: newtonmiku/wespeek:latest
    pull_policy: always
    container_name: wespeek
    restart: unless-stopped
    ports:
      - "7000:7000"
    volumes:
      - ./data:/data
    environment:
      - WSPEEK_ADDR=:7000
      - WSPEEK_STORE_IMAGES=true
      - WSPEEK_ALLOW_UPLOAD=true
      - WSPEEK_UPLOAD_DIR=/data/uploads
      - TZ=Asia/Shanghai
  